-- ============================================================================
-- LuxeWay Agentic AI — Database Schema
-- SQL Server DDL with indexes, partitioning, and retention policy
-- ============================================================================

USE LuxeWay;
GO

-- ── 1. PredictionHistory ─────────────────────────────────────────────────────
-- Stores every prediction made by any agent or ML model.
-- Partitioned by MONTH on predicted_at for efficient time-range queries.

CREATE TABLE dbo.PredictionHistory (
    prediction_id    UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    model_name       NVARCHAR(100)    NOT NULL,  -- 'AnomalyDetection' | 'ChurnPrediction' | ...
    agent_name       NVARCHAR(100)    NULL,       -- Which agent triggered this prediction
    input_hash       NVARCHAR(64)     NOT NULL,  -- SHA256 of input for deduplication
    input_summary    NVARCHAR(MAX)    NULL,       -- JSON summary (PII-masked)
    output_json      NVARCHAR(MAX)    NOT NULL,  -- Full prediction output
    confidence_score DECIMAL(5,4)     NULL,      -- 0.0–1.0
    predicted_at     DATETIME2(3)     NOT NULL DEFAULT SYSUTCDATETIME(),
    expires_at       DATETIME2(3)     NULL,       -- For TTL-based retention
    run_id           NVARCHAR(36)     NULL,       -- Correlation with AgentExecutionLog
    is_active        BIT              NOT NULL DEFAULT 1,
    CONSTRAINT PK_PredictionHistory PRIMARY KEY NONCLUSTERED (prediction_id, predicted_at)
)
ON [PRIMARY];

-- Clustered columnstore for analytics workloads
CREATE CLUSTERED COLUMNSTORE INDEX CCI_PredictionHistory
    ON dbo.PredictionHistory;

-- Time-range queries
CREATE INDEX IX_PredictionHistory_ModelDate
    ON dbo.PredictionHistory (model_name, predicted_at DESC)
    INCLUDE (confidence_score, run_id);

-- Run correlation
CREATE INDEX IX_PredictionHistory_RunId
    ON dbo.PredictionHistory (run_id)
    WHERE run_id IS NOT NULL;

-- Retention: delete predictions older than 90 days (run as scheduled job)
-- EXEC sp_delete_predictions_older_than 90;

GO

-- ── 2. AgentExecutionLog ─────────────────────────────────────────────────────
-- Records every agent invocation: timing, status, errors.

CREATE TABLE dbo.AgentExecutionLog (
    log_id           UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    run_id           NVARCHAR(36)     NOT NULL,
    agent_name       NVARCHAR(100)    NOT NULL,
    pattern_type     NVARCHAR(50)     NOT NULL,  -- 'REACTIVE'|'AUTONOMOUS'|'REASONING'|'MULTI_AGENT'|'TOOL_USING'
    status           NVARCHAR(20)     NOT NULL,  -- 'RUNNING'|'SUCCESS'|'FAILED'|'SKIPPED'|'HUMAN_REVIEW'
    started_at       DATETIME2(3)     NOT NULL,
    completed_at     DATETIME2(3)     NULL,
    duration_ms      DECIMAL(10,2)    NULL,
    input_tokens     INT              NOT NULL DEFAULT 0,
    output_tokens    INT              NOT NULL DEFAULT 0,
    error_message    NVARCHAR(MAX)    NULL,
    metadata_json    NVARCHAR(MAX)    NULL,  -- agent-specific context
    triggered_by     NVARCHAR(100)    NULL,  -- 'SCHEDULER'|'API'|'ORCHESTRATOR'
    correlation_id   NVARCHAR(36)     NULL,
    CONSTRAINT PK_AgentExecutionLog PRIMARY KEY (log_id)
);

-- Query by run
CREATE INDEX IX_AgentExecLog_RunId
    ON dbo.AgentExecutionLog (run_id, agent_name);

-- Performance monitoring
CREATE INDEX IX_AgentExecLog_StatusDate
    ON dbo.AgentExecutionLog (status, started_at DESC)
    INCLUDE (agent_name, duration_ms);

GO

-- ── 3. DemandForecast ─────────────────────────────────────────────────────────
-- Stores demand forecasts generated by DemandAgent.

CREATE TABLE dbo.DemandForecast (
    forecast_id             UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    run_id                  NVARCHAR(36)     NOT NULL,
    forecast_date           DATE             NOT NULL,  -- The predicted date
    predicted_bookings      DECIMAL(10,2)    NOT NULL,
    lower_bound             DECIMAL(10,2)    NOT NULL,
    upper_bound             DECIMAL(10,2)    NOT NULL,
    peak_day                NVARCHAR(10)     NULL,
    avg_daily_demand        DECIMAL(10,2)    NULL,
    demand_increase_pct     DECIMAL(6,2)     NULL,
    horizon_type            NVARCHAR(20)     NOT NULL,  -- 'SHORT_TERM_7D'|'MEDIUM_TERM_14D'|'LONG_TERM_30D'
    created_at              DATETIME2(3)     NOT NULL DEFAULT SYSUTCDATETIME(),
    is_active               BIT              NOT NULL DEFAULT 1,
    CONSTRAINT PK_DemandForecast PRIMARY KEY (forecast_id)
);

CREATE INDEX IX_DemandForecast_Date
    ON dbo.DemandForecast (forecast_date DESC, horizon_type)
    INCLUDE (predicted_bookings, demand_increase_pct);

GO

-- ── 4. FraudDetection ─────────────────────────────────────────────────────────
-- Stores fraud/anomaly flags from AnomalyAgent and FraudTool.

CREATE TABLE dbo.FraudDetection (
    fraud_id         UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    run_id           NVARCHAR(36)     NOT NULL,
    entity_type      NVARCHAR(50)     NOT NULL,  -- 'BOOKING'|'TRANSACTION'|'USER'|'REVENUE'|'BOOKINGS'
    entity_id        NVARCHAR(36)     NULL,
    detection_date   DATE             NOT NULL,
    metric_type      NVARCHAR(50)     NULL,      -- 'REVENUE'|'BOOKINGS'
    actual_value     DECIMAL(18,2)    NULL,
    expected_value   DECIMAL(18,2)    NULL,
    z_score          DECIMAL(8,4)     NULL,
    severity         NVARCHAR(20)     NOT NULL,  -- 'WARNING'|'CRITICAL'
    status           NVARCHAR(20)     NOT NULL DEFAULT 'OPEN',  -- 'OPEN'|'REVIEWED'|'DISMISSED'
    reviewed_by      NVARCHAR(100)    NULL,
    reviewed_at      DATETIME2(3)     NULL,
    review_notes     NVARCHAR(MAX)    NULL,
    created_at       DATETIME2(3)     NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_FraudDetection PRIMARY KEY (fraud_id)
);

CREATE INDEX IX_FraudDetection_Severity
    ON dbo.FraudDetection (severity, status, created_at DESC);

CREATE INDEX IX_FraudDetection_EntityDate
    ON dbo.FraudDetection (entity_type, detection_date DESC);

GO

-- ── 5. PriceAdjustment ────────────────────────────────────────────────────────
-- Records all pricing recommendations and their application status.

CREATE TABLE dbo.PriceAdjustment (
    adjustment_id      UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    run_id             NVARCHAR(36)     NOT NULL,
    vehicle_type       NVARCHAR(50)     NOT NULL,
    current_price      DECIMAL(10,2)    NOT NULL,
    recommended_price  DECIMAL(10,2)    NOT NULL,
    change_pct         DECIMAL(6,2)     NOT NULL,
    rationale          NVARCHAR(MAX)    NULL,
    valid_from         DATETIME2(3)     NOT NULL DEFAULT SYSUTCDATETIME(),
    valid_until        DATETIME2(3)     NULL,
    status             NVARCHAR(20)     NOT NULL DEFAULT 'PENDING',  -- 'PENDING'|'APPLIED'|'REJECTED'|'EXPIRED'
    applied_by         NVARCHAR(100)    NULL,
    applied_at         DATETIME2(3)     NULL,
    requires_approval  BIT              NOT NULL DEFAULT 1,
    approved_by        NVARCHAR(100)    NULL,
    approved_at        DATETIME2(3)     NULL,
    created_at         DATETIME2(3)     NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_PriceAdjustment PRIMARY KEY (adjustment_id)
);

CREATE INDEX IX_PriceAdjustment_VehicleStatus
    ON dbo.PriceAdjustment (vehicle_type, status, created_at DESC);

CREATE INDEX IX_PriceAdjustment_ValidPeriod
    ON dbo.PriceAdjustment (valid_from, valid_until)
    WHERE status = 'APPLIED';

GO

-- ── 6. ChurnCampaign ─────────────────────────────────────────────────────────
-- Tracks churn retention campaigns generated by ChurnAgent.

CREATE TABLE dbo.ChurnCampaign (
    campaign_id            UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    run_id                 NVARCHAR(36)     NOT NULL,
    customer_id            NVARCHAR(36)     NOT NULL,
    display_name           NVARCHAR(200)    NOT NULL,
    email_hash             NVARCHAR(64)     NOT NULL,  -- SHA256 of email (PII masking)
    churn_score            DECIMAL(5,2)     NOT NULL,
    risk_level             NVARCHAR(20)     NOT NULL,  -- 'CRITICAL'|'HIGH'|'MEDIUM'
    campaign_type          NVARCHAR(50)     NOT NULL,  -- 'VIP_DISCOUNT'|'LOYALTY_POINTS'|'WINBACK_EMAIL'
    discount_pct           DECIMAL(5,2)     NULL,
    estimated_retention    DECIMAL(5,4)     NULL,
    reasoning              NVARCHAR(MAX)    NULL,
    status                 NVARCHAR(20)     NOT NULL DEFAULT 'PENDING',  -- 'PENDING'|'SENT'|'CONVERTED'|'FAILED'
    sent_at                DATETIME2(3)     NULL,
    converted_at           DATETIME2(3)     NULL,
    created_at             DATETIME2(3)     NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ChurnCampaign PRIMARY KEY (campaign_id)
);

CREATE INDEX IX_ChurnCampaign_RiskStatus
    ON dbo.ChurnCampaign (risk_level, status, created_at DESC);

CREATE INDEX IX_ChurnCampaign_Customer
    ON dbo.ChurnCampaign (customer_id, created_at DESC);

-- Retention: Archive campaigns older than 180 days
-- EXEC sp_archive_churn_campaigns 180;

GO

-- ── Retention Policy Stored Procedure ─────────────────────────────────────────

CREATE OR ALTER PROCEDURE dbo.sp_agent_data_retention
    @retention_days_predictions INT = 90,
    @retention_days_execution   INT = 180,
    @retention_days_demand      INT = 60,
    @retention_days_fraud       INT = 365,
    @retention_days_pricing     INT = 90,
    @retention_days_churn       INT = 180
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @cutoff_predictions DATETIME2 = DATEADD(DAY, -@retention_days_predictions, SYSUTCDATETIME());
    DECLARE @cutoff_execution   DATETIME2 = DATEADD(DAY, -@retention_days_execution, SYSUTCDATETIME());
    DECLARE @cutoff_demand      DATETIME2 = DATEADD(DAY, -@retention_days_demand, SYSUTCDATETIME());

    DELETE FROM dbo.PredictionHistory WHERE predicted_at < @cutoff_predictions;
    DELETE FROM dbo.AgentExecutionLog  WHERE started_at  < @cutoff_execution;
    DELETE FROM dbo.DemandForecast     WHERE created_at  < @cutoff_demand;

    PRINT 'Retention policy applied successfully.';
END;
GO

-- ── Sample seed data for testing ──────────────────────────────────────────────

INSERT INTO dbo.AgentExecutionLog
    (run_id, agent_name, pattern_type, status, started_at, completed_at, duration_ms, triggered_by)
VALUES
    (NEWID(), 'HealthAgent',       'REACTIVE',       'SUCCESS', SYSUTCDATETIME(), SYSUTCDATETIME(), 42.5,   'SCHEDULER'),
    (NEWID(), 'AnomalyAgent',      'AUTONOMOUS',     'SUCCESS', SYSUTCDATETIME(), SYSUTCDATETIME(), 215.3,  'SCHEDULER'),
    (NEWID(), 'DemandAgent',       'MULTI_AGENT',    'SUCCESS', SYSUTCDATETIME(), SYSUTCDATETIME(), 890.7,  'API'),
    (NEWID(), 'RevenueAgent',      'TOOL_USING',     'SUCCESS', SYSUTCDATETIME(), SYSUTCDATETIME(), 634.2,  'ORCHESTRATOR'),
    (NEWID(), 'UtilizationAgent',  'REASONING',      'SUCCESS', SYSUTCDATETIME(), SYSUTCDATETIME(), 520.1,  'ORCHESTRATOR'),
    (NEWID(), 'ChurnAgent',        'REASONING',      'SUCCESS', SYSUTCDATETIME(), SYSUTCDATETIME(), 445.8,  'ORCHESTRATOR');
GO
