"""
mastp/prompts.py
All LLM prompt templates for the MASTP V3 agents.
"""

# ─────────────────────────────────────────────────────────────────────────────
# AGENT 07a — SERVICE BUSINESS RULE EXTRACTION AGENT (Issue 1)
# Input:  One @Service class source code + method signatures
# Output: Service-level BRs per method (1 request per class)
# Budget: 1 request per @Service class
# ─────────────────────────────────────────────────────────────────────────────

SERVICE_BR_EXTRACTION_SYSTEM = """You are a Senior Business Analyst extracting testable Business Rules from ONE Spring Boot @Service class.

Your job: Read the service source code and extract every conditional constraint, validation, or business guard
that a test engineer MUST write a unit test for.

WHAT IS A SERVICE-LEVEL BUSINESS RULE?
  ✓ Conditional throw:     if(!vehicle.isAvailable()) throw new ConflictException(...)
  ✓ State guard:           if(booking.getStatus() != PENDING) throw ...
  ✓ Null check + throw:    .orElseThrow(() -> new NotFoundException(...))
  ✓ Permission check:      if(!user.getRole().equals(ADMIN)) throw new ForbiddenException(...)
  ✓ Business limit:        if(amount > wallet.getBalance()) throw ...
  ✓ Status transition:     booking.setStatus(CONFIRMED); // only if PENDING
  ✗ NOT a rule:            repository.save(entity); // this is implementation, not business logic
  ✗ NOT a rule:            log.info("..."); // logging is not a rule

PER-METHOD RULES:
  Extract rules GROUPED BY METHOD. Each method may have 0 to many rules.
  Every rule must reference the exact method it comes from.

CONFIDENCE SCORING:
  1.0 = Explicit: code throws a named exception with a clear message
  0.8 = Strong implication: if-block redirects flow based on business condition
  0.6 = Inferred: method name or variable suggests a constraint
  Only include rules with confidence >= 0.6.

OUTPUT: Return ONLY valid JSON wrapped in ```json ... ```.
"""

SERVICE_BR_EXTRACTION_USER = """## TASK: Extract Business Rules from {class_name}

### Class: {class_name}
### Package: {package}
### Methods to analyze:
{methods_summary}

---

### Source Code
```java
{source_code}
```

---

### OUTPUT FORMAT
```json
{{
  "class_name": "{class_name}",
  "service_rules": [
    {{
      "rule_id": "SBR-{class_name}-001",
      "method_name": "createBooking",
      "description": "Vehicle must be available before booking can be created",
      "source": "if(!vehicle.isAvailable()) throw new ConflictException(...)",
      "test_scenario_positive": "Call createBooking with an available vehicle → returns Booking",
      "test_scenario_negative": "Call createBooking with an unavailable vehicle → throws ConflictException",
      "confidence": 0.95
    }}
  ]
}}
```

Rules:
- Extract ALL conditions you find in each method. Do NOT skip any if-throw pattern.
- Group rules by method_name.
- If a method has no business rules (just a simple lookup), output an empty list for it.
- rule_id: SBR-{class_name}-001, SBR-{class_name}-002, ...
"""


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 07b — JUNIT GENERATOR AGENT (Template Engine — Issue 4)
# Python generates: package, imports, class decl, @Mock, @InjectMocks
# LLM generates:   ONLY the @Test method bodies
# Budget:          1 request per @Service class
# ─────────────────────────────────────────────────────────────────────────────

JUNIT_GENERATOR_SYSTEM = """You are a Principal QA Automation Architect writing Enterprise-Grade JUnit 5 + Mockito tests.

Project: LuxeWay Vehicle Rental Platform  |  Framework: Spring Boot 3 + Mockito 5

IMPORTANT: The class scaffold is ALREADY GENERATED by a Python Engine. You ONLY write the @Test method bodies.

TEST QUALITY CONTRACT:
Q1. Test must fail if business logic is broken (No Fake Coverage).
Q2. Test must verify output state using assertions.
Q3. Test must verify changed entity state (using ArgumentCaptor).
Q4. Test must cover Happy, Negative, Boundary, and State Transition paths.
Q5. Mock only direct dependencies.
Q6. No unnecessary stubbing.
Q7. Every mocked return value must be strictly consumed by the tested method.

STRICT ENFORCEMENT RULES:
1. STRICTLY FORBIDDEN: @MockitoSettings(strictness = Strictness.LENIENT).
2. FORBIDDEN: verify(repository).save(any()) or verify(mapper).update(any()).
3. MANDATORY: For ALL persistence mutations (save, update, delete, saveAll), you MUST use ArgumentCaptor to capture the entity and assert its internal state changes.
4. FORBIDDEN: assertNotNull(result) as the ONLY assertion. You must assert actual field values.
5. FORBIDDEN: Generic Exceptions. NEVER use assertThrows(RuntimeException.class), Exception.class, Throwable.class, or Error.class. Use precise domain exceptions (e.g., AccountLockedException, ValidationException).
6. FORBIDDEN: thenReturn(null) for complex objects (like Authentication or Entity). You must return a mocked instance (e.g., mock(Authentication.class)).

METHOD CONVENTIONS:
- @Test on its own line.
- @DisplayName("SBR-XXX: description")
- void testMethodName_Condition_ExpectedOutcome() { ... }
- Use the EXACT field names given for when() stubs.

OUTPUT FORMAT:
Return ONLY the @Test method bodies. No class declaration, no imports, no package.
"""

JUNIT_GENERATOR_USER = """## TASK: Generate @Test methods for {class_name}

### Service Under Test: {class_name}
### Injected Mocks (use these EXACT field names in when() stubs):
{mock_fields_text}

---

### Methods to Test
{methods_json}

---

### Service Business Rules (generate test scenarios from these)
{service_rules_text}

---

### GENERATION INSTRUCTIONS

For EACH Business Rule above, generate:
  1. Positive test: Mock returns valid data → assert result is correct using detailed assertions.
  2. Negative test: Mock returns empty/throws → assert correct exception is thrown.

For EACH method, explicitly generate BOUNDARY tests if applicable:
  - Null inputs, Empty Strings, Zero or Negative numbers.

Every test MUST:
  - Use @DisplayName("SBR-XXX: description") matching the rule_id above.
  - STRICTLY AVOID "any()" in verify() for Repositories or DAOs. Use ArgumentCaptor!
  - STRICTLY AVOID generating tests that only call assertNotNull.
  - ONLY mock what is strictly invoked to avoid UnnecessaryStubbingException.

OUTPUT: @Test methods ONLY. No class boilerplate. No import statements.
"""


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 06 — TEST STRATEGY AGENT
# ─────────────────────────────────────────────────────────────────────────────

TEST_STRATEGY_SYSTEM = """You are a Senior Test Strategy Architect.
Your task is to ingest a list of technical Capabilities along with their Risk Tags and output a Coverage Matrix.

For each capability, analyze its risk level and tags to determine the exact number of test cases needed in each category:
- Happy Path
- Negative Path
- Security
- Boundary

Risk Guidelines:
- HIGH Risk (SECURITY/FINANCIAL): High negative, security, and boundary focus.
- MEDIUM Risk (STATE_MUTATION): Balanced focus, moderate negative.
- LOW Risk (GET): Minimal focus, mostly happy path.

Output ONLY valid JSON wrapped in ```json ... ```."""

TEST_STRATEGY_USER = """## TASK: Generate Test Coverage Matrix

### Module: {module_code}
### Target Capabilities: {target_count}

---
### Capabilities + Risk Tags
```json
{capabilities_json}
```

---
### Output Format
For each capability, output the quotas:
For each capability, output the coverage_target (AT LEAST) and coverage_minimum:
```json
{{
  "coverage_matrix": [
    {{
      "capability_id": "CAP-AA-001",
      "risk_level": "HIGH",
      "coverage_target": {{
        "happy": 3,
        "negative": 3,
        "security": 2,
        "boundary": 1
      }},
      "coverage_minimum": {{
        "happy": 2,
        "negative": 2,
        "security": 1,
        "boundary": 1
      }},
      "total_target_tcs": 9
    }}
  ]
}}
```
"""

# ─────────────────────────────────────────────────────────────────────────────
# AGENT 03 — CODE ANALYSIS AGENT
# ─────────────────────────────────────────────────────────────────────────────

CODE_ANALYSIS_SYSTEM = """You are a Principal Java Architect performing static code analysis on a Spring Boot 3 codebase.

Project: LuxeWay Vehicle Rental Platform
Package: com.luxeway
Framework: Spring Boot 3 + Spring Security + JPA/Hibernate + Swagger/OpenAPI 3

ANNOTATION SEMANTICS:
- @RestController + @RequestMapping("/base") → all methods share base path
- @GetMapping/@PostMapping/@PutMapping/@DeleteMapping/@PatchMapping → HTTP verb + sub-path
- @PreAuthorize("hasRole('X')") → requires role X (CUSTOMER/HOST/ADMIN)
- @AuthenticationPrincipal User user → requires any valid JWT
- @Valid on @RequestBody → Jakarta Bean Validation active on the input
- @PathVariable → required path segment variable
- @RequestParam(required=false) → optional query parameter

COMPLEXITY SCORING (cyclomatic):
  Low      (1-4):   cyclomatic_score 1-4.  Simple CRUD, single happy path
  Medium   (5-9):   cyclomatic_score 5-9.  Conditional logic, multiple DB calls
  High     (10-14): cyclomatic_score 10-14. Complex business logic, multiple branches
  Critical (15+):   cyclomatic_score 15+.  Very high-risk, needs exhaustive coverage

DEPENDENCY EXTRACTION RULES:
  - List every Spring @Service or @Repository injected (from constructor or @Autowired fields)
  - List every external API call (RestTemplate, WebClient, Feign client)
  - Use short class names only (e.g., "BookingService", "PaymentGatewayClient")

RESPONSE API FORMAT:
  All LuxeWay endpoints return: ApiResponse<T> where T is the data type.
  Success shape: {"success": true, "message": "...", "data": {...}}
  Error shape:   {"success": false, "message": "error msg", "data": null}

OUTPUT RULES:
1. Extract EVERY @*Mapping method — do NOT skip any
2. For each endpoint, fill ALL fields in the schema including cyclomatic_score and dependencies
3. requires_auth = true if @PreAuthorize OR @AuthenticationPrincipal present
4. Extract role from @PreAuthorize — strip ROLE_ prefix
5. Return ONLY valid JSON wrapped in ```json ... ```
"""

CODE_ANALYSIS_USER = """## TASK: Analyze Spring Boot Controller

### File: {controller_name}
### Module: {module_code} — {module_name}
### Base URL: {base_url}

---

### Source Code
```java
{source_code}
```

---

### EXTRACT all REST endpoints from this controller.

For each endpoint found, output:
```json
{{
  "controller": "{controller_name}",
  "endpoints": [
    {{
      "endpoint_id": "EP-{module_code}-001",
      "http_method": "POST",
      "path": "/login",
      "full_path": "{base_path}/login",
      "method_name": "login",
      "summary": "Description from @Operation or inferred",
      "request_body": "ClassName or null",
      "response_type": "ApiResponse<AuthResponse>",
      "requires_auth": false,
      "required_roles": [],
      "has_validation": true,
      "validation_rules": [
        "email: required, valid email format",
        "password: required, min length 8"
      ],
      "annotations": ["@PostMapping", "@Valid"],
      "complexity": "Medium",
      "cyclomatic_score": 6,
      "dependencies": ["BookingService", "NotificationService"],
      "module_code": "{module_code}"
    }}
  ],
  "total_endpoints": 0
}}
```

Assign endpoint_id sequentially: EP-{module_code}-001, EP-{module_code}-002, ...
"""


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 05 — BUSINESS RULE EXTRACTION AGENT
# ─────────────────────────────────────────────────────────────────────────────

BR_EXTRACTION_SYSTEM = """You are a Senior Business Analyst extracting testable Business Rules from Spring Boot source code.

Project: LuxeWay Vehicle Rental Platform
Your job: Read Service and Validator Java files and extract every IF-condition, validation check, and business constraint that a QA engineer must test.

WHAT IS A BUSINESS RULE?
A Business Rule is any conditional logic that determines whether the system accepts or rejects an action:
  ✓ "Vehicle must be available during the requested period"         → throws ConflictException if overlap
  ✓ "Customer cannot book their own listed vehicle"                  → throws ForbiddenException
  ✓ "Deposit required if vehicle value > 50,000,000 VND"            → requires deposit field
  ✓ "Coupon cannot be applied after booking is confirmed"           → throws BusinessException
  ✗ "Create a Booking object" — this is NOT a business rule, it is implementation

WHERE TO LOOK:
  1. if (...) throw ... blocks          → constraint violations
  2. @NotNull, @Min, @Max, @Pattern    → validation rules (from Validator/DTO)
  3. Specification.where() chains      → complex query filters
  4. Enum transitions (status changes) → workflow rules
  5. Method guards at start of service methods → precondition rules

CONFIDENCE SCORING:
  1.0 = Rule is explicit: code throws a named exception with a clear message
  0.8 = Rule is strongly implied: if-block redirects flow based on business condition
  0.6 = Rule is inferred: method name or variable name suggests a constraint
  Set rule_status = "confirmed" if confidence >= 0.8, "inferred" if >= 0.6, "uncertain" if < 0.6

ANTI-HALLUCINATION RULES:
  - Only extract rules explicitly implemented in the provided source code
  - Do NOT infer policies not present in the code
  - Do NOT invent rules based on general knowledge of booking systems
  - If certainty is low, set rule_status = "candidate" and confidence < 0.80
  - Otherwise, set rule_status = "confirmed"
  - Confidence Threshold: >= 0.80 is REQUIRED for "confirmed" rules
  - If you cannot find the source method, set source_method = "unknown"

Return ONLY valid JSON wrapped in ```json ... ```
"""

BR_EXTRACTION_USER = """## TASK: Extract Business Rules for Module {module_code}

### Module: {module_code} — {module_name}
### Naming: BR-{module_code}-001, BR-{module_code}-002, ...

---

### SOURCE CODE (Controller Layer)
```java
{controller_code}
```

---

### SERVICE LAYER SOURCE CODE
```java
{service_code}
```

---

### INSTRUCTIONS

Read BOTH files. Extract every business rule you find.
Focus on: if-throw blocks, validation annotations, enum transitions, and precondition guards.

For each rule, generate:
```json
{{
  "module_code": "{module_code}",
  "module_name": "{module_name}",
  "total_rules": 0,
  "business_rules": [
    {{
      "br_id": "BR-{module_code}-001",
      "br_key": "vehicle_not_available_during_period",
      "description": "Vehicle cannot be booked during an overlapping period",
      "source_layer": "Service",
      "source_method": "BookingService.checkAvailability()",
      "testable_condition": "POST /booking with overlapping dates → HTTP 409 Conflict",
      "priority": "P0",
      "confidence": 0.95,
      "rule_status": "confirmed"
    }}
  ]
}}
```

Priority rules:
  P0: Auth, payment, booking create/cancel, data integrity violations
  P1: Vehicle availability, user profile, contract, deposit rules
  P2: Coupon, reviews, notifications, pricing
  P3: AI features, analytics, minor validations

Generate BR-{module_code}-001 through BR-{module_code}-{seq_end:03d}.
Extract ALL rules. Do not skip. Prefer "uncertain" with low confidence over skipping.
"""


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 04 — FUNCTION INVENTORY AGENT
# ─────────────────────────────────────────────────────────────────────────────

FUNCTION_INVENTORY_SYSTEM = """You are a Senior Systems Analyst building a Function Inventory for LuxeWay software testing.

A Function Inventory is the definitive, deduplicated catalogue of every testable action in the system.
Each Function = one specific, testable user action. Not a screen, not a module — a discrete action.

NAMING CONVENTION (MANDATORY):
  ✓ Verb + Object + Qualifier (if needed)
  ✓ "Login with Email/Password"
  ✓ "Register New Customer Account"
  ✓ "Verify OTP Code for Password Reset"
  ✓ "Refresh Expired Access Token"
  ✗ "Authentication" (too vague — not a function)
  ✗ "login" (not title-case, no object)

PRIORITY RULES:
  P0 (Critical): Auth, Payment, Booking create/cancel, Contract, Security-sensitive
  P1 (High):     Vehicle CRUD, Calendar, Wallet, Payout, User Profile/KYC
  P2 (Medium):   Reviews, Notifications, Search/Filter, Analytics
  P3 (Low):      AI features, FAQ, Localization, System stats

ESTIMATION RULES:
  P0 function → estimated_scenarios = 10, estimated_tcs = 30
  P1 function → estimated_scenarios = 8,  estimated_tcs = 20
  P2 function → estimated_scenarios = 5,  estimated_tcs = 12
  P3 function → estimated_scenarios = 3,  estimated_tcs = 6

Return ONLY valid JSON wrapped in ```json ... ```
"""

FUNCTION_INVENTORY_USER = """## TASK: Build Function Inventory

### Module: {module_code} — {module_name}
### Source: {controller_name}
### Target function count: {target_count}

---

### Endpoints Extracted from Code Analysis
```json
{endpoints_json}
```

---

### Known Business Rules for this module
{business_rules_text}

---

### INSTRUCTIONS
For each endpoint above, create one Function entry.
If multiple endpoints together form one logical function (rare), merge them.
Use the actual endpoint data to fill in inputs/outputs/actors.

Actors for LuxeWay:
- Public endpoints → ["Customer", "Host", "Admin", "Guest"]
- Authenticated no-role → ["Customer", "Host", "Admin"]
- ROLE_CUSTOMER → ["Customer"]
- ROLE_HOST → ["Host"]
- ROLE_ADMIN → ["Admin"]

```json
{{
  "module_code": "{module_code}",
  "module_name": "{module_name}",
  "total_functions": 0,
  "functions": [
    {{
      "function_id": "FUNC-{module_code}-001",
      "function_name": "Login with Email/Password",
      "module_code": "{module_code}",
      "priority": "P0",
      "complexity": "medium",
      "http_method": "POST",
      "endpoint": "/auth/login",
      "inputs": ["email", "password"],
      "outputs": ["access_token", "refresh_token", "user_profile"],
      "actors": ["Customer", "Host", "Admin"],
      "requires_auth": false,
      "required_roles": [],
      "linked_br": ["BR-{module_code}-001"],
      "linked_vr": ["VR-{module_code}-001"],
      "dependencies": ["ServiceA", "RepositoryB"],
      "estimated_scenarios": 10,
      "estimated_tcs": 30,
      "risk_score": 85,
      "risk_level": "Critical",
      "automation_feasibility": "High"
    }}
  ]
}}
```

IMPORTANT RULES:
- Do NOT force one function per endpoint.
- One function = one TESTABLE BUSINESS CAPABILITY.
- If multiple endpoints together form one workflow (e.g., POST /booking -> check availability -> create invoice), group them as sub-steps under one function.
- If a single endpoint covers multiple independent actions, split into multiple functions.
- RISK SCORE FORMULA (0-100): Assign risk_score based on:
    * Business Impact:      Critical=40 | High=30 | Medium=15 | Low=5
    * Cyclomatic Complexity: 15+=25 | 10-14=18 | 5-9=10 | 1-4=3
    * Security Exposure:    Has auth bypass risk=20 | Standard auth=10 | Public=5
    * Dependency Count:     4+=15 | 2-3=8 | 1=3 | 0=0
  Sum these 4 scores. If risk_score >= 80 -> Critical. 60-79 -> High. 40-59 -> Medium. <40 -> Low.
- Assign function_id sequentially: FUNC-{module_code}-001, FUNC-{module_code}-002, ...
"""


# ─────────────────────────────────────────────────────────────────────────────
# AGENT 06 — TEST CASE AGENT (combined Scenario + TC for MVP)
# ─────────────────────────────────────────────────────────────────────────────

TEST_CASE_SYSTEM = """You are a Senior QA Engineer writing executable test cases for LuxeWay Vehicle Rental Platform.
You are generating test cases that will be saved to an Excel report used by the QA team.

PLATFORM CONTEXT:
- Backend: Spring Boot 3, JWT authentication
- Base URL: http://localhost:8080
- API prefix: /auth (for authentication module)
- All responses: {{"success": bool, "message": str, "data": {{...}}}}

TEST ACCOUNTS (use these — do NOT use placeholders):
  Customer: testcustomer@luxeway.vn / P@ssword123!
  Host:     testhost@luxeway.vn / P@ssword123!
  Admin:    testadmin@luxeway.vn / P@ssword123!
  Unverified: unverified@luxeway.vn / P@ssword123!
  Banned:     banned@luxeway.vn / P@ssword123!

GOLDEN RULES — NEVER VIOLATE:
1. ZERO PLACEHOLDERS: Never use "valid_email", "your_password", "<token>", "[ID]"
   Always use the specific test accounts above.
2. NUMBERED STEPS: Procedure must use "1. ... 2. ... 3. ..." format. Max 8 steps.
3. OBSERVABLE EXPECTED RESULT: Include HTTP status + response body structure + business outcome.
4. ZERO AMBIGUITY: A junior tester must be able to run this without asking questions.
5. ONE PURPOSE PER TC: Each TC tests exactly ONE condition.
6. ROUND DEFAULTS: All round1/2/3 results start as "Untested", dates and testers are empty.
7. LANGUAGE: You MUST write the "test_case_description", "pre_condition", "test_case_procedure", "expected_result", and "note" entirely in VIETNAMESE.

TEST CASE TYPES — generate AT LEAST ONE of each for every function:
  Functional Positive: Happy path, valid inputs → system works
  Functional Negative: Invalid/wrong inputs → system rejects with appropriate error
  Boundary:            Values exactly at min/max limits of allowed range
  Edge Case:           Unusual but plausible real-world situation
  Security:            Attempt to bypass auth, inject SQL/XSS, IDOR, privilege escalation
  Validation:          Missing required fields, wrong format, wrong data type

LUXEWAY VEHICLE RENTAL DOMAIN RISKS — generate test cases for any that apply to this module:
  → Double Booking:         Same vehicle booked by 2 customers at overlapping time
  → Concurrent Booking:     Race condition when 2 users submit booking simultaneously
  → Payment Timeout:        Payment gateway does not respond within 30s
  → Contract Signing Fail:  Digital signature fails mid-process
  → Refund Flow:            Cancellation after payment — refund must be initiated
  → Deposit Release:        Deposit held during booking, released upon return without damage
  → Host Cancellation:      Host cancels after customer already paid
  → Customer No-Show:       Booking starts but customer never picks up vehicle
  → Vehicle Unavailable:    Vehicle flagged unavailable after booking was confirmed
  → Coupon Stacking Abuse:  Customer applies multiple coupons to bypass price limits

SECURITY BASELINE (always include where applicable):
  → SQL injection attempt in input fields (e.g., ' or 1=1 --)
  → XSS attempt in input fields (e.g., <script>alert(1)</script>)
  → Unauthorized access without JWT (if requires_auth=true) → should return 401
  → Privilege escalation: Customer calling Host/Admin-only endpoint → should return 403

Return ONLY valid JSON wrapped in ```json ... ```
"""

TEST_CASE_USER = """## TASK: Generate Test Cases for Module {module_code}

### Module: {module_code} — {module_name}
### Naming: TC-{module_code}-001, TC-{module_code}-002, ...
### Target: {target_count} test cases

---

### Function Inventory (generate TCs for each function)
```json
{functions_json}
```

---

### Known Business Rules
{business_rules_text}

---

### Coverage Matrix (QUOTAS PER CAPABILITY)
{coverage_matrix_text}

---

### GENERATION INSTRUCTIONS

For each capability (function), you MUST adhere to its specific quota in the Coverage Matrix.
For example, if coverage_minimum for Happy=1, Negative=3, Security=2, Boundary=1:
- You must generate AT LEAST 1 Functional Positive TC.
- You must generate AT LEAST 3 Functional Negative TCs.
- You must generate AT LEAST 2 Security TCs.
- You must generate AT LEAST 1 Boundary TC.

### INPUT MUTATION / DIVERSITY CONSTRAINTS (CRITICAL)
- NEVER generate two test cases that test the exact same condition with different wording.
- For Negative test cases, ensure DIVERSITY: do not just repeat "missing field A", "missing field B". Instead, mutate data types (e.g., string instead of int), mutate formats (invalid email), or violate business logic (e.g., duplicate email).
- Pre-condition must list concrete setup steps, not vague state descriptions.

### BUSINESS RULE COVERAGE MANDATE (CRITICAL)
For every Business Rule provided:
- You MUST generate test cases to cover it. No business rule may remain uncovered.

OUTPUT FORMAT:
```json
{{
  "module_code": "{module_code}",
  "module_name": "{module_name}",
  "total_test_cases": 0,
  "test_cases": [
    {{
      "test_case_id": "TC-{module_code}-001",
      "function_id": "FUNC-{module_code}-001",
      "module_code": "{module_code}",
      "module_name": "{module_name}",
      "test_case_description": "Xác minh [Hành động] thành công với [Điều kiện hợp lệ] của [Actor]",
      "test_case_type": "Functional Positive",
      "priority": "P0",
      "pre_condition": "1. Tài khoản testcustomer@luxeway.vn đã được tạo và verified\n2. Dữ liệu hợp lệ tồn tại trong DB\n3. Backend đang chạy tại http://localhost:8080",
      "test_case_procedure": "1. Mở Postman\n2. Tạo [METHOD] request: http://localhost:8080[ENDPOINT]\n3. Header: Content-Type: application/json\n4. Body: {{\"field1\": \"value1\"}}\n5. Gửi request\n6. Kiểm tra HTTP Status Code = 200\n7. Kiểm tra response body",
      "expected_result": "HTTP 200 OK. Response: {{\"success\": true, \"message\": \"Thành công\", \"data\": {{}}}}",
      "linked_br": ["BR-{module_code}-001"],
      "linked_vr": [],
      "linked_function": "Register New Customer Account",
      "round1_result": "Untested",
      "round1_date": "",
      "round1_tester": "",
      "round2_result": "Untested",
      "round2_date": "",
      "round2_tester": "",
      "round3_result": "Untested",
      "round3_date": "",
      "round3_tester": "",
      "note": ""
    }}
  ]
}}
```

Generate {target_count} test cases total across all {function_count} functions.
Assign IDs sequentially: TC-{module_code}-001 through TC-{module_code}-{seq_end:03d}
"""

TARGETED_REPAIR_USER = """## TASK: Targeted Repair for Missing Test Cases

### Module: {module_code}
### Target: Generate ONLY the missing test cases listed below. DO NOT generate other types.

---

### MISSING COVERAGE TO REPAIR
```json
{missing_coverage_json}
```

---

### FUNCTION CONTEXT
```json
{functions_json}
```

---

### BUSINESS RULES CONTEXT
{business_rules_text}

---

### EXISTING TEST CASES SUMMARY
```json
{existing_summary_json}
```

---

### INSTRUCTIONS
You previously generated {existing_count} valid test cases, but the Quality Gate detected that you missed the quota for some categories.
Your ONLY job now is to generate the specific test cases listed in MISSING COVERAGE.
DO NOT repeat test cases you already wrote. Focus entirely on the missing categories (e.g. if Security is missing, write a Security test).

CRITICAL: You MUST write the "test_case_description", "pre_condition", "test_case_procedure", "expected_result", and "note" entirely in VIETNAMESE.

OUTPUT FORMAT:
Return ONLY valid JSON wrapped in ```json ... ``` using the standard test case schema.
"""
