SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
GO
-- ============================================================
-- LuxeWay: Add 42 real vehicles (26 cars + 16 motorbikes)
-- DB: SQL Server (car_rental_platform)
-- Owner: owner-user-id-003 (seeded default owner)
-- Run: sqlcmd -S localhost,1433 -U sa -P 123456 -d car_rental_platform -i add_missing_vehicles.sql
-- Each INSERT uses SELECT...WHERE NOT EXISTS to skip duplicates
-- ============================================================

SELECT COUNT(*) AS current_total FROM vehicles;
GO

-- ====== CARS (26 vehicles) ======

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Toyota Vios 1.5E','Toyota','Vios 1.5E',2022,'ECONOMY','CAR','Toyota Vios 1.5E so tu dong, tiet kiem nhien lieu, thich hop di chuyen trong thanh pho.',550000,1650000,'Ho Chi Minh City','Vietnam','45 Dinh Tien Hoang, Binh Thanh, TP. HCM',10.8031,106.7117,5,4,'AUTOMATIC','GASOLINE','51G-C11111','/images/cars/toyota_vios.jpg','AVAILABLE','APPROVED',1,0,1,1,50000,4.70,22,38,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51G-C11111');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Toyota Camry 2.5G','Toyota','Camry 2.5G',2023,'SEDAN','CAR','Toyota Camry 2.5G noi that sang trong, Toyota Safety Sense, giao xe tan noi noi thanh.',1400000,4200000,'Hanoi','Vietnam','15 Nguyen Thai Hoc, Ba Dinh, Ha Noi',21.0311,105.8430,5,4,'AUTOMATIC','GASOLINE','30E-C22222','/images/cars/caramy_2.5Q.avif','AVAILABLE','APPROVED',1,1,1,1,60000,4.80,15,28,0,1,1,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='30E-C22222');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Toyota Fortuner 2.4G','Toyota','Fortuner 2.4G',2022,'SUV','CAR','Toyota Fortuner 2.4G 7 cho gam cao, thich hop gia dinh da ngoai, xe manh me cung cap.',1300000,3900000,'Da Nang','Vietnam','72 Phan Chau Trinh, Hai Chau, Da Nang',16.0580,108.2210,7,4,'AUTOMATIC','DIESEL','43H-C33333','/images/cars/toyota_forluner.jpg','AVAILABLE','APPROVED',1,1,1,1,50000,4.75,18,32,0,1,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='43H-C33333');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Toyota Innova 2.0E','Toyota','Innova 2.0E',2021,'FAMILY','CAR','Toyota Innova 2.0E 7 cho so san, khoang hanh ly rong rai, ben bi, nhom ban di xa.',900000,2700000,'Ho Chi Minh City','Vietnam','200 Le Van Sy, Quan 3, TP. HCM',10.7866,106.6847,7,4,'MANUAL','GASOLINE','51H-C44444','/images/cars/toyota_innova.jpg','AVAILABLE','APPROVED',1,0,0,1,50000,4.60,12,25,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51H-C44444');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Mazda 3 Sport 2.0L','Mazda','Mazda 3 Sport',2023,'SEDAN','CAR','Mazda 3 Sport 2.0L thiet ke Kodo dep mat, lai the thao, an toan i-Activesense.',800000,2400000,'Nha Trang','Vietnam','18 Tran Phu, Loc Tho, Nha Trang',12.2430,109.1955,5,4,'AUTOMATIC','GASOLINE','79C-C55555','/images/cars/Mazda_mazda3.jpg','AVAILABLE','APPROVED',1,0,1,1,40000,4.65,10,20,0,0,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='79C-C55555');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Mazda CX-8 Luxury','Mazda','CX-8 Luxury',2023,'SUV','CAR','Mazda CX-8 Luxury 7 cho SUV 3 hang ghe sang trong, am thanh BOSE cao cap.',1600000,4800000,'Ho Chi Minh City','Vietnam','88 Nguyen Huu Canh, Binh Thanh, TP. HCM',10.7893,106.7263,7,4,'AUTOMATIC','GASOLINE','51K-C66666','/images/cars/Madaz _CX8.jpg','AVAILABLE','APPROVED',1,1,1,1,60000,4.85,16,30,0,1,1,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51K-C66666');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Mercedes-Benz E300 AMG','Mercedes-Benz','E300 AMG',2023,'BUSINESS','CAR','Mercedes-Benz E300 AMG Line the thao, MBUX thong minh, ly tuong cho doanh nhan.',4000000,12000000,'Ho Chi Minh City','Vietnam','33 Ton Duc Thang, Quan 1, TP. HCM',10.7760,106.7040,5,4,'AUTOMATIC','GASOLINE','51A-C77777','/images/cars/Mereedes_benz_e300.jpg','AVAILABLE','APPROVED',1,1,0,1,100000,4.90,9,18,1,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51A-C77777');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Mercedes-Benz GLC 300','Mercedes-Benz','GLC 300',2022,'BUSINESS','CAR','Mercedes-Benz GLC 300 4Matic SUV hang sang, van hanh manh me, an toan chu dong.',3500000,10500000,'Hanoi','Vietnam','50 Ly Thuong Kiet, Hoan Kiem, Ha Noi',21.0216,105.8438,5,4,'AUTOMATIC','GASOLINE','30F-C88888','/images/cars/mereedes_benz_glc300.jpg','AVAILABLE','APPROVED',1,1,0,1,80000,4.88,11,22,1,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='30F-C88888');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','VinFast VF9 Plus','VinFast','VF9 Plus',2024,'ELECTRIC_CAR','CAR','VinFast VF9 Plus SUV dien 7 cho, pham vi 438km, ADAS tan tien, sac nhanh DC.',2500000,7500000,'Hanoi','Vietnam','VinFast Tran Duy Hung, Cau Giay, Ha Noi',21.0146,105.7983,7,4,'AUTOMATIC','ELECTRIC','30V-C99999','/images/cars/vinfast_v9.jpg','AVAILABLE','APPROVED',1,1,1,1,80000,4.82,8,15,0,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='30V-C99999');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','BMW 320i M Sport','BMW','320i M Sport',2023,'BUSINESS','CAR','BMW 320i M Sport van hanh the thao sac ben, noi that M Sport, iDrive 8 thong minh.',2000000,6000000,'Ho Chi Minh City','Vietnam','127 Nguyen Van Troi, Phu Nhuan, TP. HCM',10.7950,106.6780,5,4,'AUTOMATIC','GASOLINE','51B-D10001','/images/cars/BMW_320i.jpg','AVAILABLE','APPROVED',1,1,1,1,70000,4.85,13,25,0,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51B-D10001');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','BMW X5 xDrive30d','BMW','X5 xDrive30d',2022,'SUV','CAR','BMW X5 xDrive30d 7 cho cao cap, diesel manh me, AWD bam duong tot, iDrive 7.',4000000,12000000,'Hanoi','Vietnam','360 Kim Ma, Ba Dinh, Ha Noi',21.0332,105.8268,7,4,'AUTOMATIC','DIESEL','30G-D20002','/images/cars/BMW_X5.jpg','AVAILABLE','APPROVED',1,1,0,1,100000,4.88,7,14,1,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='30G-D20002');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Audi Q5 40 TFSI','Audi','Q5 40 TFSI',2022,'BUSINESS','CAR','Audi Q5 40 TFSI quattro SUV hang sang, dong co 2.0T 204 ma luc, Virtual Cockpit.',2800000,8400000,'Da Nang','Vietnam','250 Tran Phu, Hai Chau, Da Nang',16.0626,108.2190,5,4,'AUTOMATIC','GASOLINE','43A-D30003','/images/cars/audi_Q5.jpg','AVAILABLE','APPROVED',1,1,0,1,80000,4.83,9,17,0,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='43A-D30003');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Porsche Cayenne S','Porsche','Cayenne S',2022,'BUSINESS','CAR','Porsche Cayenne S SUV sieu sang, V8 440HP, he thong treo PDCC thich ung.',7500000,22500000,'Ho Chi Minh City','Vietnam','1 Nam Quoc Cang, Quan 1, TP. HCM',10.7710,106.6941,5,4,'AUTOMATIC','GASOLINE','51A-D40004','/images/cars/porsche_cayenne.jpg','AVAILABLE','APPROVED',1,1,0,1,150000,4.95,5,10,1,1,1,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51A-D40004');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Hyundai Accent 1.4 AT','Hyundai','Accent 1.4 AT',2022,'ECONOMY','CAR','Hyundai Accent 1.4 AT tiet kiem nhien lieu, xe nho gon de do trong pho.',500000,1500000,'Ho Chi Minh City','Vietnam','120 Cach Mang Thang 8, Quan 10, TP. HCM',10.7740,106.6669,5,4,'AUTOMATIC','GASOLINE','51D-D50005','/images/cars/Hyundai-Aceent.jpg','AVAILABLE','APPROVED',1,0,1,1,40000,4.55,20,40,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51D-D50005');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Hyundai Tucson 2.0 AT','Hyundai','Tucson 2.0 AT',2022,'SUV','CAR','Hyundai Tucson 2.0 AT the he moi, SmartSense, van hanh em va on dinh.',1000000,3000000,'Hanoi','Vietnam','95 Nguyen Phong Sac, Cau Giay, Ha Noi',21.0380,105.7918,5,4,'AUTOMATIC','GASOLINE','30H-D60006','/images/cars/hyundai_tuscon.jpg','AVAILABLE','APPROVED',1,0,1,1,50000,4.70,14,26,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='30H-D60006');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Kia Cerato 2.0 AT','Kia','Cerato 2.0 AT',2021,'SEDAN','CAR','Kia Cerato 2.0 AT Premium sedan the thao, noi that dep, gia hop ly.',700000,2100000,'Ho Chi Minh City','Vietnam','88 Dien Bien Phu, Binh Thanh, TP. HCM',10.8014,106.7138,5,4,'AUTOMATIC','GASOLINE','51F-D70007','/images/cars/kia_morning.jpg','AVAILABLE','APPROVED',1,0,1,1,40000,4.60,16,30,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51F-D70007');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Kia Carnival 2.2D','Kia','Carnival 2.2D',2022,'FAMILY','CAR','Kia Carnival 2.2D 8 cho MPV sang trong, hang ghe VIP reclining, man hinh 12.3 inch.',2000000,6000000,'Ho Chi Minh City','Vietnam','250 Hoang Van Thu, Tan Binh, TP. HCM',10.8090,106.6660,7,4,'AUTOMATIC','DIESEL','51G-D80008','/images/cars/kia_carnival.jpg','AVAILABLE','APPROVED',1,1,1,1,70000,4.80,10,20,0,1,1,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51G-D80008');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Ford Ranger Wildtrak','Ford','Ranger Wildtrak',2022,'PICKUP','CAR','Ford Ranger Wildtrak 4x4 ban tai 5 cho, gam cao vuot dia hinh, moment xoan khung.',1100000,3300000,'Da Lat','Vietnam','5 Thong Nhat, Phuong 10, Da Lat',11.9352,108.4516,5,4,'AUTOMATIC','DIESEL','49A-D90009','/images/cars/ford_ranger.jpg','AVAILABLE','APPROVED',1,0,1,1,60000,4.72,18,35,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='49A-D90009');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Ford Everest Titanium','Ford','Everest Titanium',2023,'SUV','CAR','Ford Everest Titanium 7 cho SUV co lon gam cao, diesel, SYNC4 thong minh.',1500000,4500000,'Nha Trang','Vietnam','90 23 Thang 10, Nha Trang',12.2384,109.1912,7,4,'AUTOMATIC','DIESEL','79B-E10010','/images/cars/ford_everest.jpg','AVAILABLE','APPROVED',1,0,1,1,60000,4.75,12,22,0,1,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='79B-E10010');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Mitsubishi Xpander Cross','Mitsubishi','Xpander Cross',2022,'FAMILY','CAR','Mitsubishi Xpander Cross 7 cho gam cao 210mm, op nhua den bao ve, xe gia dinh nang dong.',800000,2400000,'Ho Chi Minh City','Vietnam','505 Pham Van Dong, Binh Thanh, TP. HCM',10.8190,106.6987,7,4,'AUTOMATIC','GASOLINE','51H-E20020','/images/cars/Mitsibishi_xpannder.jpg','AVAILABLE','APPROVED',1,0,0,1,50000,4.65,14,28,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51H-E20020');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Lexus RX 350 F-Sport','Lexus','RX 350 F-Sport',2022,'BUSINESS','CAR','Lexus RX 350 F-Sport SUV sieu sang Nhat Ban, da cao cap Mark Levinson, van hanh tuyet voi.',4500000,13500000,'Ho Chi Minh City','Vietnam','16 Nguyen Hue, Quan 1, TP. HCM',10.7733,106.7025,5,4,'AUTOMATIC','GASOLINE','51A-E30030','/images/cars/Lexus_Rx350.jpg','AVAILABLE','APPROVED',1,1,0,1,120000,4.92,6,12,1,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51A-E30030');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Nissan Almera VL CVT','Nissan','Almera VL CVT',2022,'ECONOMY','CAR','Nissan Almera VL sedan hang B the he moi, tang ap 1.0L, 4.9L/100km.',550000,1650000,'Hanoi','Vietnam','18 Thai Ha, Dong Da, Ha Noi',21.0260,105.8278,5,4,'AUTOMATIC','GASOLINE','30J-E40040','/images/cars/Nissan_Almera.jpg','AVAILABLE','APPROVED',1,0,1,1,40000,4.58,18,35,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='30J-E40040');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda CR-V 1.5L Turbo','Honda','CR-V 1.5L Turbo',2022,'SUV','CAR','Honda CR-V 1.5L Turbo AWD 7 cho, VTEC Turbo manh me, 561L hanh ly, Honda Sensing.',1200000,3600000,'Da Nang','Vietnam','140 Nguyen Van Linh, Da Nang',16.0471,108.2013,7,4,'AUTOMATIC','GASOLINE','43G-E50050','/images/cars/Honda_CrV.jpg','AVAILABLE','APPROVED',1,0,1,1,50000,4.77,13,24,0,1,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='43G-E50050');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Porsche Macan S 3.0T','Porsche','Macan S',2022,'BUSINESS','CAR','Porsche Macan S dong co 3.0T 354HP, SUV the thao dich thuc, phanh gom PCCB.',5500000,16500000,'Ho Chi Minh City','Vietnam','700 Pham Van Dong, Binh Thanh, TP. HCM',10.8337,106.7019,5,4,'AUTOMATIC','GASOLINE','51B-E60060','/images/cars/porsche_macan.jpg','AVAILABLE','APPROVED',1,1,0,1,150000,4.93,4,8,0,1,0,1,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51B-E60060');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','VinFast Fadil 1.4L AT','VinFast','Fadil 1.4L AT',2022,'ECONOMY','CAR','VinFast Fadil xe Viet gon nhe, tiet kiem xang, phu hop phu nu di chuyen trong pho.',480000,1440000,'Ho Chi Minh City','Vietnam','185 Nguyen Dinh Chieu, Quan 3, TP. HCM',10.7840,106.6878,5,4,'AUTOMATIC','GASOLINE','51D-E70070','/images/cars/vinfast_fadil.jpg','AVAILABLE','APPROVED',1,0,1,1,40000,4.52,24,45,0,0,0,0,0,0,0,0,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='51D-E70070');

GO

-- ====== MOTORBIKES (16 vehicles) ======

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda SH 150i 2023','Honda','SH 150i',2023,'SCOOTER','MOTORBIKE','Honda SH 150i phong cach thuong luu, PGMFI toi uu, giam xoc truoc nguoc, den LED.',380000,760000,'Ho Chi Minh City','Vietnam','320 Dien Bien Phu, Quan 3, TP. HCM',10.7890,106.6880,2,0,'AUTOMATIC','GASOLINE','59M1-F10001','/images/motorbikes/Honda_Sh_150i.jpg','AVAILABLE','APPROVED',1,1,1,1,30000,4.85,18,42,0,0,0,0,1,1,1,0,150,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='59M1-F10001');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda SH 150i Ha Noi','Honda','SH 150i',2022,'SCOOTER','MOTORBIKE','Honda SH 150i tay ga cao cap, ABS, ISS tiet kiem nhien lieu, xe dep khong ty vet.',350000,700000,'Hanoi','Vietnam','60 Ba Trieu, Hoan Kiem, Ha Noi',21.0191,105.8529,2,0,'AUTOMATIC','GASOLINE','29M1-F20002','/images/motorbikes/Honda_Sh_150i.jpg','AVAILABLE','APPROVED',1,1,1,1,25000,4.80,15,35,0,0,0,0,1,1,0,0,150,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='29M1-F20002');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda Vision 2023','Honda','Vision',2023,'SCOOTER','MOTORBIKE','Honda Vision 2023 mau trang nga thanh lich, cop xe 18.6L, phanh CBS an toan.',130000,260000,'Ho Chi Minh City','Vietnam','100 Le Duc Tho, Go Vap, TP. HCM',10.8249,106.6780,2,0,'AUTOMATIC','GASOLINE','59N1-F30003','/images/motorbikes/Honda_vision.jpg','AVAILABLE','APPROVED',1,0,1,1,20000,4.65,25,50,0,0,0,0,1,1,1,0,110,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='59N1-F30003');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda Vision 2022 Da Nang','Honda','Vision',2022,'SCOOTER','MOTORBIKE','Honda Vision tay ga pho thong tiet kiem xang, nhe nhang de lai cho phu nu va sinh vien.',120000,240000,'Da Nang','Vietnam','35 Nguyen Chi Thanh, Hai Chau, Da Nang',16.0605,108.2159,2,0,'AUTOMATIC','GASOLINE','43N1-F40004','/images/motorbikes/Honda_vision.jpg','AVAILABLE','APPROVED',1,0,1,1,15000,4.60,22,44,0,0,0,0,1,0,1,0,110,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='43N1-F40004');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda Air Blade 125 2023','Honda','Air Blade',2023,'SCOOTER','MOTORBIKE','Honda Air Blade 125 ca tinh the thao, Smart Key, cop 18L, ABS/CBS, xe cho gioi tre.',160000,320000,'Ho Chi Minh City','Vietnam','55 Pho Quang, Tan Binh, TP. HCM',10.8020,106.6530,2,0,'AUTOMATIC','GASOLINE','59P1-F50005','/images/motorbikes/Honda_air_blade.jpg','AVAILABLE','APPROVED',1,0,1,1,20000,4.70,20,40,0,0,0,0,1,1,0,0,125,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='59P1-F50005');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda Air Blade 150 Premium','Honda','Air Blade',2022,'SCOOTER','MOTORBIKE','Honda Air Blade 150 phien ban dac biet, dong co manh 150cc, son tem the thao.',180000,360000,'Nha Trang','Vietnam','12 Quang Trung, Nha Trang',12.2479,109.1967,2,0,'AUTOMATIC','GASOLINE','79N1-F60006','/images/motorbikes/Honda_air_blade.jpg','AVAILABLE','APPROVED',1,0,1,1,20000,4.65,14,30,0,0,0,0,1,1,1,0,150,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='79N1-F60006');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Honda Winner X 150','Honda','Winner X',2023,'MANUAL_MOTORCYCLE','MOTORBIKE','Honda Winner X con tay 150cc ABS, khung xe toi uu, 1.8L/100km tiet kiem.',170000,340000,'Da Lat','Vietnam','10 Hoang Dieu 2, Da Lat',11.9396,108.4389,2,0,'MANUAL','GASOLINE','49N1-F70007','/images/motorbikes/Honda_winer_X.jpg','AVAILABLE','APPROVED',1,0,1,1,20000,4.72,16,32,0,0,0,0,1,1,1,0,150,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='49N1-F70007');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Yamaha Exciter 155 VVA','Yamaha','Exciter 155',2023,'MANUAL_MOTORCYCLE','MOTORBIKE','Yamaha Exciter 155 VVA con tay the thao, VVA toi uu momen xoan, ABS. Vua con tay VN.',170000,340000,'Ho Chi Minh City','Vietnam','888 Quang Trung, Go Vap, TP. HCM',10.8284,106.6744,2,0,'MANUAL','GASOLINE','59Q1-F80008','/images/motorbikes/Yamaha_eceiter_155.jpg','AVAILABLE','APPROVED',1,0,1,1,20000,4.75,19,38,0,0,0,0,1,1,0,0,155,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='59Q1-F80008');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Yamaha NVX 155 Ha Noi','Yamaha','NVX 155',2022,'SCOOTER','MOTORBIKE','Yamaha NVX 155 VVA Smart Key, tay ga the thao, cop 25L, SMG khoi dong em.',190000,380000,'Hanoi','Vietnam','285 Tay Son, Dong Da, Ha Noi',21.0133,105.8406,2,0,'AUTOMATIC','GASOLINE','29Q1-F90009','/images/motorbikes/Yamaha_NVX_155.webp','AVAILABLE','APPROVED',1,0,1,1,25000,4.78,14,28,0,0,0,0,1,1,1,0,155,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='29Q1-F90009');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Yamaha Grande 125 Hybrid','Yamaha','Grande',2023,'SCOOTER','MOTORBIKE','Yamaha Grande 125 Hybrid tay ga sang trong nhat phan khuc 125cc, SMG thong minh.',160000,320000,'Ho Chi Minh City','Vietnam','456 Cach Mang Thang 8, Quan 10, TP. HCM',10.7721,106.6588,2,0,'AUTOMATIC','GASOLINE','59R1-G10010','/images/motorbikes/Yamaha_Grande.jpg','AVAILABLE','APPROVED',1,0,1,1,20000,4.70,16,32,0,0,0,0,1,1,1,0,125,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='59R1-G10010');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Kawasaki Ninja 400 ABS','Kawasaki','Ninja 400',2022,'SPORT_BIKE','MOTORBIKE','Kawasaki Ninja 400 ABS sportbike 400cc, parallel twin 399cc 45HP, ninja thuan tuy.',900000,1800000,'Ho Chi Minh City','Vietnam','78 Pham Ngoc Thach, Quan 3, TP. HCM',10.7887,106.6983,2,0,'MANUAL','GASOLINE','59T1-G30030','/images/motorbikes/Kawaski_ninja_400.jpg','AVAILABLE','APPROVED',1,0,0,1,30000,4.88,8,16,0,0,0,0,1,1,0,1,399,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='59T1-G30030');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','KTM Duke 390 2023','KTM','Duke 390',2023,'SPORT_BIKE','MOTORBIKE','KTM Duke 390 mang 373.2cc 43HP, khung thep nhe, phanh Brembo, man hinh TFT 5 inch.',950000,1900000,'Hanoi','Vietnam','45 Lang Ha, Ba Dinh, Ha Noi',21.0261,105.8188,2,0,'MANUAL','GASOLINE','29T1-G40040','/images/motorbikes/KTM_Duke_390.jpg','AVAILABLE','APPROVED',1,0,0,1,30000,4.90,6,12,0,0,0,0,1,1,0,1,373,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='29T1-G40040');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Royal Enfield Classic 350','Royal Enfield','Classic 350',2022,'CLASSIC_BIKE','MOTORBIKE','Royal Enfield Classic 350 xe co dien huyen thoai Anh Quoc, am thanh dong co dac trung.',750000,1500000,'Da Lat','Vietnam','3 Hung Vuong, Da Lat',11.9430,108.4370,2,0,'MANUAL','GASOLINE','49U1-G50050','/images/motorbikes/Royal_Enfield_classic-250.jpg','AVAILABLE','APPROVED',1,1,0,1,25000,4.82,10,18,0,0,0,0,1,1,1,1,349,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='49U1-G50050');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','Royal Enfield Himalayan 411','Royal Enfield','Himalayan',2022,'ADVENTURE_BIKE','MOTORBIKE','Royal Enfield Himalayan 411cc adventure dia hinh, gam cao 220mm, kham pha nui deo.',850000,1700000,'Da Lat','Vietnam','22 Le Hong Phong, Da Lat',11.9448,108.4398,2,0,'MANUAL','GASOLINE','49V1-G60060','/images/motorbikes/Royal_Enfield_himalayan.jpg','AVAILABLE','APPROVED',1,1,0,1,25000,4.80,8,15,0,0,0,0,1,1,1,1,411,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='49V1-G60060');

INSERT INTO vehicles (id,owner_id,name,brand,model,[year],category,vehicle_type,description,price_per_day,deposit,city,country,address,latitude,longitude,seats,doors,transmission,fuel_type,license_plate,thumbnail_url,status,approval_status,is_verified,is_featured,instant_book,delivery_available,delivery_fee,rating,total_reviews,total_bookings,has_chauffeur,airport_delivery,wedding_rental,business_rental,has_helmet,has_phone_holder,has_raincoat,has_touring_package,engine_cc,is_locked,min_rental_days,max_rental_days,advance_booking_days)
SELECT NEWID(),'owner-user-id-003','SYM Attila Victoria 125','SYM','Attila',2021,'SCOOTER','MOTORBIKE','SYM Attila Victoria 125cc tay ga pho bien, nhe nhang, cop xe rong, 1.6L/100km.',120000,240000,'Ho Chi Minh City','Vietnam','500 Nguyen Thi Dinh, Quan 2, TP. HCM',10.7910,106.7450,2,0,'AUTOMATIC','GASOLINE','59W1-G70070','/images/motorbikes/SYM_attila.jpg','AVAILABLE','APPROVED',1,0,1,1,15000,4.55,28,55,0,0,0,0,1,0,1,0,125,0,1,30,365
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE license_plate='59W1-G70070');

GO

-- ====== VERIFY FINAL COUNT ======
SELECT 
    COUNT(*) AS total_vehicles,
    SUM(CASE WHEN vehicle_type = 'CAR' THEN 1 ELSE 0 END) AS total_cars,
    SUM(CASE WHEN vehicle_type = 'MOTORBIKE' THEN 1 ELSE 0 END) AS total_motorbikes
FROM vehicles
WHERE status = 'AVAILABLE' AND approval_status = 'APPROVED';

PRINT 'Vehicle seeding complete! Check total above.';



